var TeamData={PL:{color:"#8A2BE2",matches:[{date:"2012-06-08",against:"GR",result:[1,1],goals:[{minute:17,country:"PL",player:"Lewandowski"},{minute:51,country:"GR",player:"Salpingidis"}]},{date:"2012-06-12",against:"RU",result:[1,1],goals:[{minute:37,country:"RU",player:"Dzagoev"},{minute:57,country:"PL",player:"B\u0142aszczykowski"}]},{date:"2012-06-16",against:"CZ",result:[0,1],goals:[{minute:72,country:"CZ",player:"Jir\u00e1\u010dek"}]}]},GR:{color:"#00008B",matches:[{date:"2012-06-08",against:"PL",
result:[1,1],goals:[{minute:17,country:"PL",player:"Lewandowski"},{minute:51,country:"GR",player:"Salpingidis"}]},{date:"2012-06-12",against:"CZ",result:[1,2],goals:[{minute:3,country:"CZ",player:"Jir\u00e1\u010dek"},{minute:6,country:"CZ",player:"Pila\u0159"},{minute:53,country:"GR",player:"Gekas"}]},{date:"2012-06-16",against:"RU",result:[1,0],goals:[{minute:47,country:"GR",player:"Karagounis"}]},{date:"2012-06-22",against:"DE",result:[2,4],goals:[{minute:39,country:"DE",player:"Lahm",offset:1},
{minute:55,country:"GR",player:"Samaras",offset:4},{minute:61,country:"DE",player:"Khedira",offset:4},{minute:68,country:"DE",player:"Klose",offset:4},{minute:74,country:"DE",player:"Reus",offset:4},{minute:89,country:"GR",player:"Salpingidis",offset:4}]}]},RU:{color:"#DC143C",matches:[{date:"2012-06-08",against:"CZ",result:[4,1],goals:[{minute:15,country:"RU",player:"Dzagoev"},{minute:24,country:"RU",player:"Shirokov"},{minute:52,country:"CZ",player:"Pila\u0159"},{minute:79,country:"RU",player:"Dzagoev"},
{minute:82,country:"RU",player:"Pavlyuchenko"}]},{date:"2012-06-12",against:"PL",result:[1,1],goals:[{minute:37,country:"RU",player:"Dzagoev"},{minute:57,country:"PL",player:"B\u0142aszczykowski"}]},{date:"2012-06-16",against:"GR",result:[0,1],goals:[{minute:47,country:"GR",player:"Karagounis"}]}]},CZ:{color:"#FF7F50",matches:[{date:"2012-06-08",against:"RU",result:[1,4],goals:[{minute:15,country:"RU",player:"Dzagoev"},{minute:24,country:"RU",player:"Shirokov"},{minute:52,country:"CZ",player:"Pila\u0159"},
{minute:79,country:"RU",player:"Dzagoev"},{minute:82,country:"RU",player:"Pavlyuchenko"}]},{date:"2012-06-12",against:"GR",result:[2,1],goals:[{minute:3,country:"CZ",player:"Jir\u00e1\u010dek"},{minute:6,country:"CZ",player:"Pila\u0159"},{minute:53,country:"GR",player:"Gekas"}]},{date:"2012-06-16",against:"PL",result:[1,0],goals:[{minute:72,country:"CZ",player:"Jir\u00e1\u010dek"}]},{date:"2012-06-21",against:"PT",result:[0,1],goals:[{minute:79,country:"PT",player:"Cristiano Ronaldo",offset:1}]}]},
NL:{color:"#FFA500",matches:[{date:"2012-06-09",against:"DK",result:[0,1],goals:[{minute:24,country:"DK",player:"Krohn-Dehli"}]},{date:"2012-06-13",against:"DE",result:[1,2],goals:[{minute:24,country:"DE",player:"Gomez"},{minute:38,country:"DE",player:"Gomez"},{minute:73,country:"NL",player:"Van Persie"}]},{date:"2012-06-17",against:"PT",result:[1,2],goals:[{minute:11,country:"NL",player:"Van der Vaart"},{minute:28,country:"PT",player:"Cristiano Ronaldo"},{minute:74,country:"PT",player:"Cristiano Ronaldo",
offset:-1}]}]},DK:{color:"#2F4F4F",matches:[{date:"2012-06-09",against:"NL",result:[1,0],goals:[{minute:24,country:"DK",player:"Krohn-Dehli"}]},{date:"2012-06-13",against:"PT",result:[2,3],goals:[{minute:24,country:"PT",player:"Pepe"},{minute:36,country:"PT",player:"H\u00e9lder Postiga"},{minute:41,country:"DK",player:"Bendtner"},{minute:80,country:"DK",player:"Bendtner",offset:1},{minute:87,country:"PT",player:"Varela",offset:1}]},{date:"2012-06-17",against:"DE",result:[1,2],goals:[{minute:19,country:"DE",
player:"Podolski"},{minute:24,country:"DK",player:"Krohn-Dehli"},{minute:80,country:"DE",player:"Bender"}]}]},DE:{color:"#FFD700",matches:[{date:"2012-06-09",against:"PT",result:[1,0],goals:[{minute:72,country:"DE",player:"Gomez",offset:1}]},{date:"2012-06-13",against:"NL",result:[2,1],goals:[{minute:24,country:"DE",player:"Gomez"},{minute:38,country:"DE",player:"Gomez"},{minute:73,country:"NL",player:"Van Persie"}]},{date:"2012-06-17",against:"DK",result:[2,1],goals:[{minute:19,country:"DE",player:"Podolski"},
{minute:24,country:"DK",player:"Krohn-Dehli"},{minute:80,country:"DE",player:"Bender"}]},{date:"2012-06-22",against:"GR",result:[4,2],goals:[{minute:39,country:"DE",player:"Lahm",offset:1},{minute:55,country:"GR",player:"Samaras",offset:4},{minute:61,country:"DE",player:"Khedira",offset:4},{minute:68,country:"DE",player:"Klose",offset:4},{minute:74,country:"DE",player:"Reus",offset:4},{minute:89,country:"GR",player:"Salpingidis",offset:4}]},{date:"2012-06-28",against:"IT",result:[1,2],goals:[{minute:20,
country:"IT",player:"Balotelli",offset:2},{minute:36,country:"IT",player:"Balotelli",offset:2},{minute:92,country:"DE",player:"\u00d6zil",offset:4}]}]},PT:{color:"#006400",matches:[{date:"2012-06-09",against:"DE",result:[0,1],goals:[{minute:72,country:"DE",player:"Gomez",offset:1}]},{date:"2012-06-13",against:"DK",result:[3,2],goals:[{minute:24,country:"PT",player:"Pepe"},{minute:36,country:"PT",player:"H\u00e9lder Postiga"},{minute:41,country:"DK",player:"Bendtner"},{minute:80,country:"DK",player:"Bendtner",
offset:1},{minute:87,country:"PT",player:"Varela",offset:1}]},{date:"2012-06-17",against:"NL",result:[2,1],goals:[{minute:11,country:"NL",player:"Van der Vaart"},{minute:28,country:"PT",player:"Cristiano Ronaldo"},{minute:74,country:"PT",player:"Cristiano Ronaldo",offset:-1}]},{date:"2012-06-21",against:"CZ",result:[1,0],goals:[{minute:79,country:"PT",player:"Cristiano Ronaldo",offset:1}]},{date:"2012-06-27",against:"ES",result:[2,4],goals:[]}]},ES:{color:"#C74243",matches:[{date:"2012-06-10",against:"IT",
result:[1,1],goals:[{minute:61,country:"IT",player:"Di Natale",offset:-1},{minute:64,country:"ES",player:"F\u00e0bregas",offset:-1}]},{date:"2012-06-14",against:"IE",result:[4,0],goals:[{minute:4,country:"ES",player:"Torres"},{minute:49,country:"ES",player:"Silva"},{minute:70,country:"ES",player:"Torres"},{minute:83,country:"ES",player:"F\u00e0bregas"}]},{date:"2012-06-18",against:"HR",result:[1,0],goals:[{minute:88,country:"ES",player:"Jes\u00fas Navas"}]},{date:"2012-06-23",against:"FR",result:[2,
0],goals:[{minute:19,country:"ES",player:"Xabi Alonso"},{minute:91,country:"ES",player:"Xabi Alonso",offset:-1}]},{date:"2012-06-27",against:"PT",result:[4,2],goals:[]},{date:"2012-07-01",against:"IT",result:[4,0],goals:[{minute:14,player:"Silva",country:"ES",offset:2},{minute:41,player:"Jordi Alba",country:"ES",offset:2},{minute:84,player:"Torres",country:"ES",offset:1},{minute:88,player:"Juan Mata",country:"ES",offset:1}]}]},IT:{color:"#557EAA",matches:[{date:"2012-06-10",against:"ES",result:[1,
1],goals:[{minute:61,country:"IT",player:"Di Natale",offset:-1},{minute:64,country:"ES",player:"F\u00e0bregas",offset:-1}]},{date:"2012-06-14",against:"HR",result:[1,1],goals:[{minute:39,country:"IT",player:"Pirlo"},{minute:72,country:"HR",player:"Mand\u017euki\u0107",offset:-1}]},{date:"2012-06-18",against:"IE",result:[2,0],goals:[{minute:35,country:"IT",player:"Cassano",offset:2},{minute:90,country:"IT",player:"Balotelli",offset:2}]},{date:"2012-06-24",against:"GB",result:[4,2],goals:[]},{date:"2012-06-28",
against:"DE",result:[2,1],goals:[{minute:20,country:"IT",player:"Balotelli",offset:2},{minute:36,country:"IT",player:"Balotelli",offset:2},{minute:92,country:"DE",player:"\u00d6zil",offset:4}]},{date:"2012-07-01",against:"ES",result:[0,4],goals:[{minute:14,player:"Silva",country:"ES",offset:2},{minute:41,player:"Jordi Alba",country:"ES",offset:2},{minute:84,player:"Torres",country:"ES",offset:1},{minute:88,player:"Juan Mata",country:"ES",offset:1}]}]},IE:{color:"#70A35E",matches:[{date:"2012-06-10",
against:"HR",result:[1,3],goals:[{minute:3,country:"HR",player:"Mand\u017euki\u0107",offset:2},{minute:19,country:"IE",player:"St Ledger",offset:2},{minute:43,country:"HR",player:"Jelavi\u0107",offset:2},{minute:49,country:"HR",player:"Mand\u017euki\u0107",offset:2}]},{date:"2012-06-14",against:"ES",result:[0,4],goals:[{minute:4,country:"ES",player:"Torres"},{minute:49,country:"ES",player:"Silva"},{minute:70,country:"ES",player:"Torres"},{minute:83,country:"ES",player:"F\u00e0bregas"}]},{date:"2012-06-18",
against:"IT",result:[0,2],goals:[{minute:35,country:"IT",player:"Cassano",offset:2},{minute:90,country:"IT",player:"Balotelli",offset:2}]}]},HR:{color:"#FF69B4",matches:[{date:"2012-06-10",against:"IE",result:[3,1],goals:[{minute:3,country:"HR",player:"Mand\u017euki\u0107",offset:2},{minute:19,country:"IE",player:"St Ledger",offset:2},{minute:43,country:"HR",player:"Jelavi\u0107",offset:2},{minute:49,country:"HR",player:"Mand\u017euki\u0107",offset:2}]},{date:"2012-06-14",against:"IT",result:[1,1],
goals:[{minute:39,country:"IT",player:"Pirlo"},{minute:72,country:"HR",player:"Mand\u017euki\u0107",offset:-1}]},{date:"2012-06-18",against:"ES",result:[0,1],goals:[{minute:88,country:"ES",player:"Jes\u00fas Navas"}]}]},UA:{color:"#83548B",matches:[{date:"2012-06-11",against:"SE",result:[2,1],goals:[{minute:52,country:"SE",player:"Ibrahimovi\u0107",offset:3},{minute:55,country:"UA",player:"Shevchenko",offset:3},{minute:62,country:"UA",player:"Shevchenko",offset:3}]},{date:"2012-06-15",against:"FR",
result:[0,2],goals:[{minute:53,country:"FR",player:"M\u00e9nez",offset:-4},{minute:56,country:"FR",player:"Cabaye",offset:-3}]},{date:"2012-06-19",against:"GB",result:[0,1],goals:[{minute:48,player:"Rooney",country:"GB"}]}]},SE:{color:"#EBB056",matches:[{date:"2012-06-11",against:"UA",result:[1,2],goals:[{minute:52,country:"SE",player:"Ibrahimovi\u0107",offset:3},{minute:55,country:"UA",player:"Shevchenko",offset:3},{minute:62,country:"UA",player:"Shevchenko",offset:3}]},{date:"2012-06-15",against:"GB",
result:[2,3],goals:[{minute:23,country:"GB",player:"Carroll",offset:17},{minute:49,country:"SE",player:"Johnson",offset:17},{minute:59,country:"SE",player:"Mellberg",offset:17},{minute:64,country:"GB",player:"Walcott",offset:17},{minute:78,country:"GB",player:"Welbeck",offset:17}]},{date:"2012-06-19",against:"FR",result:[2,0],goals:[{minute:54,country:"SE",player:"Ibrahimovi\u0107",offset:2},{minute:91,country:"SE",player:"Larsson",offset:2}]}]},GB:{color:"#909291",matches:[{date:"2012-06-11",against:"FR",
result:[1,1],goals:[{minute:30,country:"GB",player:"Lescott"},{minute:39,country:"FR",player:"Nasri"}]},{date:"2012-06-15",against:"SE",result:[3,2],goals:[{minute:23,country:"GB",player:"Carroll",offset:17},{minute:49,country:"SE",player:"Johnson",offset:17},{minute:59,country:"SE",player:"Mellberg",offset:17},{minute:64,country:"GB",player:"Walcott",offset:17},{minute:78,country:"GB",player:"Welbeck",offset:17}]},{date:"2012-06-19",against:"UA",result:[1,0],goals:[{minute:48,player:"Rooney",country:"GB"}]},
{date:"2012-06-24",against:"IT",result:[2,4],goals:[]}]},FR:{color:"#416D9C",matches:[{date:"2012-06-11",against:"GB",result:[1,1],goals:[{minute:30,country:"GB",player:"Lescott"},{minute:39,country:"FR",player:"Nasri"}]},{date:"2012-06-15",against:"UA",result:[2,0],goals:[{minute:53,country:"FR",player:"M\u00e9nez",offset:-4},{minute:56,country:"FR",player:"Cabaye",offset:-3}]},{date:"2012-06-19",against:"SE",result:[0,2],goals:[{minute:54,country:"SE",player:"Ibrahimovi\u0107",offset:2},{minute:91,
country:"SE",player:"Larsson",offset:2}]},{date:"2012-06-23",against:"ES",result:[0,2],goals:[{minute:19,country:"ES",player:"Xabi Alonso"},{minute:91,country:"ES",player:"Xabi Alonso",offset:-1}]}]}},filteredTeams=Object.keys(TeamData);
function init(){function v(a){0===i&&(i=1+a,n=this,r(a))}function j(a){j.show=a;u.style.display=a?"":"none";c.style.display=a?"":"none";w[a?"addClass":"removeClass"]("filtered");a&&(c.style.top=(window.getHeight()-c.offsetHeight)/2+"px",c.style.left=(window.getWidth()-c.offsetWidth)/2+"px")}function x(a,c,h){var b=$("goals"),g=0,f=0,d;b||(b=window.G_vmlCanvasManager?G_vmlCanvasManager.initElement(document.body.appendChild(document.createElement("canvas"))):document.createElement("canvas"),b.id="goals",
setTimeout(function(){$("goals-canvas-wrapper").appendChild(b)},10));b.width=900;b.height=300;d=b.getContext("2d");d.clearRect(0,0,900,300);d.font="bold 12px 'Helvetica Neue'";d.fillStyle=d.strokeStyle="#555";h.each(function(e){var b=(e.minute<48?e.minute+(e.offset||0):e.minute+(e.offset||0)+17)/120*900;d.beginPath();if(e.country==a){d.moveTo(b,150);d.lineTo(b,0);g++}else{d.moveTo(b,150);d.lineTo(b,300);f++}d.stroke();d.closePath();e.country==a?d.fillText("'"+e.minute+" "+e.player,b+5,12*g):d.fillText("'"+
e.minute+" "+e.player,b+5,300-12*(f-1))})}function r(a){var l=n.id,h=TeamData[l].matches[a],b=h.result,g=h.against,f=$(l+"_name"),d=$(g+"_name"),e=c.getElement(".team1.name"),k=c.getElement(".team2.name"),a=n.getElements(".match")[a],o=[f.innerHTML,d.innerHTML];e.innerHTML=b[0]+" - "+o[0];k.innerHTML=b[1]+" - "+o[1];(new Request.JSON({url:"data/matches/"+a.id+"/part.json",method:"get",onSuccess:function(a){var b={label:[o[0],o[1]],color:[TeamData[l].color,TeamData[g].color],values:a},e=0,d=c.getElement(".name-wrapper.team1"),
f=c.getElement(".name-wrapper.team2");d.addEvent("click",function(){c.chart.filter(b.label[0])});f.addEvent("click",function(){c.chart.filter(b.label[1])});$$("#main-panel .name-wrapper .color").each(function(a){a.style.background=b.color[e++]});if(c.chart)e=0,c.chart.delegate.graph.eachNode(function(b){0<e&&(b.name=a[e-1].label,b.getData("next")&&(a[e]?b.setData("next",a[e].label):b.setData("next",!1)));e++}),c.chart.updateJSON(b);else{var k=new $jit.AreaChart({injectInto:"infovis",width:900,height:300,
animate:!0,Margin:{top:0,left:0,right:0,bottom:0},Events:{enable:!0,onClick:function(a){a||k.restore()}},showAggregates:!1,showLabels:!1,type:"stacked",Label:{type:"Native",size:8,family:"Arial",color:"black"},Tips:{enable:!0,onShow:function(a,b){var e=+b.value;1E6<=e?e=Math.round(e/1E5)/10+"M":1E3<=e&&(e=Math.round(e/100)/10+"K");a.innerHTML="<b>"+e+"</b> tweets for <b>"+b.name+"</b>"}},filterOnClick:!1,restoreOnRightClick:!1});k.loadJSON(b);c.canvas=k.canvas.canvases[0].canvas;c.chart=k}d={};d[l]=
b.color[0];d[h.against]=b.color[1];x(l,h.against,h.goals,d);j(!0);c.chart.canvas.getPos(!0)}})).send();s()}function s(){var a=n.getElements(".match").length,c=i;c==a?p.addClass("disabled"):p.removeClass("disabled");1==c?q.addClass("disabled"):q.removeClass("disabled");1<=c?m.removeClass("hidden"):m.addClass("hidden")}var u=$("background"),c=$("main-panel");$$("div.row");$$("div.country-name");var m=$$(".navigation")[0],w=$("container"),q=m.getElement(".previous"),p=m.getElement(".next"),t=m.getElement(".back"),
i=0,n;u.addEvent("click",function(a){t.fireEvent("click",a)});t.addEvent("click",function(){this.hasClass("disabled")||(j(!1),i=0)},!1);q.addEvent("click",function(){!this.hasClass("disabled")&&!c.chart.busy&&(i--,r(i-1),s())},!1);p.addEvent("click",function(){!this.hasClass("disabled")&&!c.chart.busy&&(i++,r(i-1),s())},!1);window.addEvent("resize",function(){j.show&&j(!0)});window.addEvent("keyup",function(a){if(j.show)switch(a.key){case "right":p.fireEvent("click",a);break;case "left":q.fireEvent("click",
a);break;case "esc":t.fireEvent("click",a)}});$$(".row-wrapper > .color").each(function(a){a.style.background=TeamData[a.getParent().getElement(".country-name").id.split("_")[0]].color});(function(){for(var a in TeamData)$(a).innerHTML=TeamData[a].matches.map(function(a,c){var b=c.date+"_"+a+"_"+c.against,g=c.result,g=g[0]-g[1],g=0==g?"Tie":0<g?"Win":"Loss";return"<div id='"+b+"' class='match'><div class='image-match' style='background-image:url(data/matches/"+b+"/match.png)'></div><div class='against-name'><span class='"+
g.toLowerCase()+"'>"+g+"</span> vs. "+$(c.against+"_name").innerHTML+"</div></div>"}.bind(this,a)).join("")})();$$(".match").addEvent("click",function(){v.call(this.getParent(),this.getParent().getElements(".match").indexOf(this))});(function(){var a,c=$$(".stream-nav a");$("all-teams").addEvent("click",function(b){b.stop();a.busy||(c.removeClass("selected"),this.addClass("selected"),filteredTeams=Object.keys(TeamData),a.filter(filteredTeams,{onComplete:function(){a.setupLabels()}}))});$("teams-qf").addEvent("click",
function(b){a.busy||(b.stop(),c.removeClass("selected"),this.addClass("selected"),filteredTeams=Object.keys(TeamData).filter(function(a){return 3<TeamData[a].matches.length}),a.filter(filteredTeams,{onComplete:function(){a.setupLabels()}}))});$("teams-nqf").addEvent("click",function(b){a.busy||(b.stop(),c.removeClass("selected"),this.addClass("selected"),filteredTeams=Object.keys(TeamData).filter(function(a){return 3>=TeamData[a].matches.length}),a.filter(filteredTeams,{onComplete:function(){a.setupLabels()}}))});
var h=new Fx.Scroll(window,{onComplete:function(){$$(".row-wrapper.selected").removeClass("selected")}});$$(".row-wrapper > a").addEvent("click",function(a){a.stop();h.toElement($("container"))});(new Request.JSON({url:"data/match-summary.json",method:"get",onSuccess:function(b){b.color=b.label.map(function(a){return TeamData[a.trim()].color});a=new $jit.StreamChart({injectInto:"stream-viz",type:window.G_vmlCanvasManager?"stacked":"smooth",animate:!1,Margin:{top:5,left:0,right:0,bottom:5},labelOffset:0,
showAggregates:!1,showLabels:!1,Tips:{enable:!0,onShow:function(a,b,c){var c=c.name.slice(0,10).split("-"),d=+b.value;1E6<=d?d=Math.round(d/1E5)/10+"M":1E3<=d&&(d=Math.round(d/100)/10+"K");a.innerHTML="<b>"+d+"</b> tweets for <b>"+$(b.name.trim()+"_name").innerHTML+"</b> on "+[c[1],c[2],c[0]].join("/")}},Events:{enable:!0,onClick:function(a){a&&(a=$(a.name.trim()).getParent(),a.addClass("selected"),h.toElement(a))}},filterOnClick:!1,restoreOnRightClick:!1,selectOnHover:!1});a.loadJSON(b);a.canvas.getPos=
function(){for(var a=this.getElement(),b=0,c=0;a&&!/^(?:html)$/i.test(a.tagName);)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return this.pos={x:b,y:c}};a.config.animate=!0;a.filter(filteredTeams,{onComplete:function(){a.setupLabels()}});var c=$("background-stream-viz");if(!c){if(window.G_vmlCanvasManager)return;c=document.createElement("canvas");c.id="background-stream-viz";$(c).inject("stream-viz","top")}c.width=900;c.height=480;var f=c.getContext("2d"),b=b.values,d=900/(b.length-1);f.lineWidth=
0.2;f.strokeStyle="#ddd";f.fillStyle="#bbb";b.each(function(a,b){f.beginPath();f.moveTo(d*b,0);f.lineTo(d*b,460);f.closePath();f.stroke();var c=a.label.split(" ")[0].split("-"),c=c[1]+"/"+c[2];f.fillText(c,d*b+5,460)})}})).send()})()}window.addEvent("domready",init);
